# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'grid_view.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QFrame, QHBoxLayout, QLabel, QLayout,
    QListWidget, QListWidgetItem, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QSlider, QSpacerItem,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QSize(1080, 720))
        MainWindow.setStyleSheet(u"/* ---------------------------------------------------------------------------\n"
"\n"
"    WARNING! File created programmatically. All changes made in this file will be lost!\n"
"\n"
"    Created by the qtsass compiler v0.4.0\n"
"\n"
"    The definitions are in the \"qdarkstyle.qss._styles.scss\" module\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"/* Light Style - QDarkStyleSheet ------------------------------------------ */\n"
"/*\n"
"\n"
"See Qt documentation:\n"
"\n"
"  - https://doc.qt.io/qt-5/stylesheet.html\n"
"  - https://doc.qt.io/qt-5/stylesheet-reference.html\n"
"  - https://doc.qt.io/qt-5/stylesheet-examples.html\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"/* Reset elements ------------------------------------------------------------\n"
"\n"
"Resetting everything helps to unify styles across different operating systems\n"
"\n"
"--------------------------------------------------------------------------- */"
                        "\n"
"* {\n"
"  padding: 0px;\n"
"  margin: 0px;\n"
"  border: 0px;\n"
"  border-style: none;\n"
"  border-image: none;\n"
"  outline: 0;\n"
"}\n"
"\n"
"/* specific reset for elements inside QToolBar */\n"
"QToolBar * {\n"
"  margin: 0px;\n"
"  padding: 0px;\n"
"}\n"
"\n"
"/* QWidget ----------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QWidget {\n"
"  background-color: #19232D;\n"
"  border: 0px solid #455364;\n"
"  padding: 0px;\n"
"  color: #DFE1E2;\n"
"  selection-background-color: #346792;\n"
"  selection-color: #DFE1E2;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #788D9C;\n"
"  selection-background-color: #26486B;\n"
"  selection-color: #788D9C;\n"
"}\n"
"\n"
"QWidget::item:selected {\n"
"  background-color: #346792;\n"
"}\n"
"\n"
"QWidget::item:hover:!selected {\n"
"  background-color: #1A72BB;\n"
"}\n"
"\n"
"/* QMainWindow --------------------------------------------"
                        "----------------\n"
"\n"
"This adjusts the splitter in the dock widget, not qsplitter\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmainwindow\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QMainWindow::separator {\n"
"  background-color: #455364;\n"
"  border: 0px solid #19232D;\n"
"  spacing: 0px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"  background-color: #60798B;\n"
"  border: 0px solid #1A72BB;\n"
"}\n"
"\n"
"QMainWindow::separator:horizontal {\n"
"  width: 5px;\n"
"  margin-top: 2px;\n"
"  margin-bottom: 2px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_separator_vertical.png\");\n"
"}\n"
"\n"
"QMainWindow::separator:vertical {\n"
"  height: 5px;\n"
"  margin-left: 2px;\n"
"  margin-right: 2px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_separator_horizontal.png\");\n"
"}\n"
"\n"
"/* QToolTip ---------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples."
                        "html#customizing-qtooltip\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolTip {\n"
"  background-color: #346792;\n"
"  color: #DFE1E2;\n"
"  /* If you remove the border property, background stops working on Windows */\n"
"  border: none;\n"
"  /* Remove padding, for fix combo box tooltip */\n"
"  padding: 0px;\n"
"  /* Remove opacity, fix #174 - may need to use RGBA */\n"
"}\n"
"\n"
"/* QStatusBar -------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qstatusbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QStatusBar {\n"
"  border: 1px solid #455364;\n"
"  /* Fixes Spyder #9120, #9121 */\n"
"  background: #455364;\n"
"  /* Fixes #205, white vertical borders separating items */\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"  border: none;\n"
"}\n"
"\n"
"QStatusBar QToolTip {\n"
"  background-color: #1A72BB;\n"
"  border: 1px solid #19232D;\n"
"  col"
                        "or: #19232D;\n"
"  /* Remove padding, for fix combo box tooltip */\n"
"  padding: 0px;\n"
"  /* Reducing transparency to read better */\n"
"  opacity: 230;\n"
"}\n"
"\n"
"QStatusBar QLabel {\n"
"  /* Fixes Spyder #9120, #9121 */\n"
"  background: transparent;\n"
"}\n"
"\n"
"/* QCheckBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qcheckbox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QCheckBox {\n"
"  background-color: #19232D;\n"
"  color: #DFE1E2;\n"
"  spacing: 4px;\n"
"  outline: none;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"}\n"
"\n"
"QCheckBox:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QCheckBox QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"  margin-left: 2px;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"\n"
"/* QGroupBox ----------------------------------------------------------"
                        "----\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qgroupbox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QGroupBox {\n"
"  font-weight: bold;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  margin-top: 6px;\n"
"  margin-bottom: 4px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  subcontrol-origin: margin;\n"
"  subcontrol-position: top left;\n"
"  left: 4px;\n"
"  padding-left: 2px;\n"
"  padding-right: 4px;\n"
"  padding-top: -4px;\n"
"}\n"
"\n"
"QGroupBox::indicator {\n"
"  margin-left: 2px;\n"
"  margin-top: 2px;\n"
"  padding: 0;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked:hover, QGroupBox::indicator:unchecked:focus, QGroupBox::indicator:unchecked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked_f"
                        "ocus.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:checked {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:checked:hover, QGroupBox::indicator:checked:focus, QGroupBox::indicator:checked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:checked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_disabled.png\");\n"
"}\n"
"\n"
"/* QRadioButton -----------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qradiobutton\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QRadioButton {\n"
"  background-color: #19232D;\n"
"  color: #DFE1E2;\n"
"  spacing: 4px;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
""
                        "  border: none;\n"
"  outline: none;\n"
"}\n"
"\n"
"QRadioButton:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QRadioButton:disabled {\n"
"  background-color: #19232D;\n"
"  color: #788D9C;\n"
"  border: none;\n"
"  outline: none;\n"
"}\n"
"\n"
"QRadioButton QWidget {\n"
"  background-color: #19232D;\n"
"  color: #DFE1E2;\n"
"  spacing: 0px;\n"
"  padding: 0px;\n"
"  outline: none;\n"
"  border: none;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"  border: none;\n"
"  outline: none;\n"
"  margin-left: 2px;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  image: url(\":/qss_icons/dark/rc/radio_unchecked.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover, QRadioButton::indicator:unchecked:focus, QRadioButton::indicator:unchecked:pressed {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_unchecked_focus.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/radio_unchecke"
                        "d_disabled.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_checked.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover, QRadioButton::indicator:checked:focus, QRadioButton::indicator:checked:pressed {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_checked_focus.png\");\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:disabled {\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_checked_disabled.png\");\n"
"}\n"
"\n"
"/* QMenuBar ---------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmenubar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QMenuBar {\n"
"  background-color: #455364;\n"
"  padding: 2px;\n"
"  border: 1px solid #19232D;\n"
"  color: #DFE1E2;\n"
"  selection-background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenuBar:focus {\n"
"  bo"
                        "rder: 1px solid #346792;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"  background: transparent;\n"
"  padding: 4px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"  padding: 4px;\n"
"  background: transparent;\n"
"  border: 0px solid #455364;\n"
"  background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"  padding: 4px;\n"
"  border: 0px solid #455364;\n"
"  background-color: #1A72BB;\n"
"  color: #DFE1E2;\n"
"  margin-bottom: 0px;\n"
"  padding-bottom: 0px;\n"
"}\n"
"\n"
"/* QMenu ------------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmenu\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QMenu {\n"
"  border: 0px solid #455364;\n"
"  color: #DFE1E2;\n"
"  margin: 0px;\n"
"  background-color: #37414F;\n"
"  selection-background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"  height: 1px;\n"
"  background-color: #60798B;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QMenu::item {\n"
" "
                        " background-color: #37414F;\n"
"  padding: 4px 24px 4px 28px;\n"
"  /* Reserve space for selection border */\n"
"  border: 1px transparent #455364;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"  color: #DFE1E2;\n"
"  background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenu::item:pressed {\n"
"  background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenu::icon {\n"
"  padding-left: 10px;\n"
"  width: 14px;\n"
"  height: 14px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"  padding-left: 8px;\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  /* non-exclusive indicator = check box style indicator (see QActionGroup::setExclusive) */\n"
"  /* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:hover, QMenu::indicator:non-exclusive:unchecked:focus, QMenu::indicator:non-exclusive:unchecked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qs"
                        "s_icons/dark/rc/checkbox_unchecked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:hover, QMenu::indicator:non-exclusive:checked:focus, QMenu::indicator:non-exclusive:checked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:indeterminate {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:indeterminate:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:in"
                        "determinate:focus, QMenu::indicator:non-exclusive:indeterminate:hover, QMenu::indicator:non-exclusive:indeterminate:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked {\n"
"  image: url(\":/qss_icons/dark/rc/radio_unchecked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:hover, QMenu::indicator:exclusive:unchecked:focus, QMenu::indicator:exclusive:unchecked:pressed {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_unchecked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/radio_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_checked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:hover, QMenu::indicator:exclusive:checked:focus, QMenu::indicator:exclusive:checked:pressed {\n"
"  border:"
                        " none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_checked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:disabled {\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_checked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::right-arrow {\n"
"  margin: 5px;\n"
"  padding-left: 12px;\n"
"  image: url(\":/qss_icons/dark/rc/arrow_right.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"}\n"
"\n"
"/* QAbstractItemView ------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qcombobox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractItemView {\n"
"  alternate-background-color: #19232D;\n"
"  color: #DFE1E2;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QAbstractItemView QLineEdit {\n"
"  padding: 2px;\n"
"}\n"
"\n"
"/* QAbstractScrollArea ----------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/style"
                        "sheet-examples.html#customizing-qabstractscrollarea\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractScrollArea {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  /* fix #159 */\n"
"  padding: 2px;\n"
"  /* remove min-height to fix #244 */\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QAbstractScrollArea:disabled {\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"/* QScrollArea ------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QScrollArea QWidget QWidget:disabled {\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"/* QScrollBar -------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qscrollbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QScrollBar:horizontal {\n"
"  height: 16px;\n"
"  margin: 2px 16px 2px 16px;"
                        "\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"  background-color: #19232D;\n"
"  width: 16px;\n"
"  margin: 16px 2px 16px 2px;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"  background-color: #60798B;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"  background-color: #346792;\n"
"  border: #346792;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  background-color: #60798B;\n"
"  border: 1px solid #455364;\n"
"  min-height: 8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"  background-color: #346792;\n"
"  border: #346792;\n"
"  border-radius: 4px;\n"
"  min-height: 8px;\n"
"}\n"
"\n"
"QScrollBar::hand"
                        "le:vertical:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"  margin: 0px 0px 0px 0px;\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_right_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover, QScrollBar::add-line:horizontal:on {\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_right.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_down_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on {\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"  height: 12px;\n"
"  width: 12px"
                        ";\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"  margin: 0px 3px 0px 3px;\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_left_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on {\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_left.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_up_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover, QScrollBar::sub-line:vertical:on {\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_up.png\");\n"
"  height: 12px;\n"
"  width"
                        ": 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"/* QTextEdit --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-specific-widgets\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTextEdit {\n"
"  background-color: #19232D;\n"
"  color: #DFE1E2;\n"
"  border-radius: 4px;\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QTextEdit:selected {\n"
"  background: #346792;\n"
"  co"
                        "lor: #455364;\n"
"}\n"
"\n"
"/* QPlainTextEdit ---------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QPlainTextEdit {\n"
"  background-color: #19232D;\n"
"  color: #DFE1E2;\n"
"  border-radius: 4px;\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QPlainTextEdit:selected {\n"
"  background: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"/* QSizeGrip --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qsizegrip\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QSizeGrip {\n"
"  background: transparent;\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  image: url(\":/qss_icons/dark/rc/window_grip.png\");\n"
"}\n"
"\n"
"/* QStackedWidget ---------------------------------------------------------\n"
"\n"
"---------------------------------"
                        "------------------------------------------ */\n"
"QStackedWidget {\n"
"  padding: 2px;\n"
"  border: 1px solid #455364;\n"
"  border: 1px solid #19232D;\n"
"}\n"
"\n"
"/* QToolBar ---------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtoolbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolBar {\n"
"  background-color: #455364;\n"
"  border-bottom: 1px solid #19232D;\n"
"  padding: 1px;\n"
"  font-weight: bold;\n"
"  spacing: 2px;\n"
"}\n"
"\n"
"QToolBar:disabled {\n"
"  /* Fixes #272 */\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"  width: 16px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_move_horizontal.png\");\n"
"}\n"
"\n"
"QToolBar::handle:vertical {\n"
"  height: 16px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_move_vertical.png\");\n"
"}\n"
"\n"
"QToolBar::separator:horizontal {\n"
"  width: 16px;\n"
"  image: url(\":/qss_icons/dark/r"
                        "c/toolbar_separator_horizontal.png\");\n"
"}\n"
"\n"
"QToolBar::separator:vertical {\n"
"  height: 16px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_separator_vertical.png\");\n"
"}\n"
"\n"
"QToolButton#qt_toolbar_ext_button {\n"
"  background: #455364;\n"
"  border: 0px;\n"
"  color: #DFE1E2;\n"
"  image: url(\":/qss_icons/dark/rc/arrow_right.png\");\n"
"}\n"
"\n"
"/* QAbstractSpinBox -------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractSpinBox {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #DFE1E2;\n"
"  /* This fixes 103, 111 /\n"
"  padding-top: 2px;\n"
"  / This fixes 103, 111 /\n"
"  padding-bottom: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-radius: 4px;\n"
"  / min-width: 5px; removed to fix 109 */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QAbstractSpinBox:hover {\n"
"  border: 1px solid #346792;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QAbstractSpin"
                        "Box:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QAbstractSpinBox:selected {\n"
"  background: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------------ */\n"
"/* DISPLAYS --------------------------------------------------------------- */\n"
"/* ------------------------------------------------------------------------ */\n"
"/* QLabel -----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qframe\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QLabel {\n"
"  background-color: #19232D;\n"
"  border: 0px solid #455364;\n"
"  padding: 2px;\n"
"  margin: 0px;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"  background-color: #19232D;\n"
"  border: 0px solid #455364;\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"/* QTextBrowser -----------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/"
                        "stylesheet-examples.html#customizing-qabstractscrollarea\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTextBrowser {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #DFE1E2;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTextBrowser:disabled {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #788D9C;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTextBrowser:hover, QTextBrowser:!hover, QTextBrowser:selected, QTextBrowser:pressed {\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"/* QGraphicsView ----------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QGraphicsView {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #DFE1E2;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QGraphicsView:disabled {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #788D9C;\n"
"  border-radiu"
                        "s: 4px;\n"
"}\n"
"\n"
"QGraphicsView:hover, QGraphicsView:!hover, QGraphicsView:selected, QGraphicsView:pressed {\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"/* QCalendarWidget --------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QCalendarWidget {\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QCalendarWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"/* QLCDNumber -------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QLCDNumber {\n"
"  background-color: #19232D;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QLCDNumber:disabled {\n"
"  background-color: #19232D;\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"/* QProgressBar -----------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qprogressbar\n"
"\n"
""
                        "--------------------------------------------------------------------------- */\n"
"QProgressBar {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #DFE1E2;\n"
"  border-radius: 4px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar:disabled {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #788D9C;\n"
"  border-radius: 4px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"  background-color: #346792;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QProgressBar::chunk:disabled {\n"
"  background-color: #26486B;\n"
"  color: #788D9C;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------------ */\n"
"/* BUTTONS ---------------------------------------------------------------- */\n"
"/* ------------------------------------------------------------------------ */\n"
"/* QPushButton ------------------------------------------------------------\n"
"\n"
"https://doc.qt"
                        ".io/qt-5/stylesheet-examples.html#customizing-qpushbutton\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QPushButton {\n"
"  background-color: #455364;\n"
"  color: #DFE1E2;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"  border: none;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"  background-color: #455364;\n"
"  color: #788D9C;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"  background-color: #60798B;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QPushButton:checked:disabled {\n"
"  background-color: #60798B;\n"
"  color: #788D9C;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QPushButton:checked:selected {\n"
"  background: #60798B;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #54687A;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #60798B;\n"
"}\n"
"\n"
"QPushButton:selected {\n"
""
                        "  background: #60798B;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QPushButton::menu-indicator {\n"
"  subcontrol-origin: padding;\n"
"  subcontrol-position: bottom right;\n"
"  bottom: 4px;\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"  /* Issue #194 #248 - Special case of QPushButton inside dialogs, for better UI */\n"
"  min-width: 80px;\n"
"}\n"
"\n"
"/* QToolButton ------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtoolbutton\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolButton {\n"
"  background-color: #455364;\n"
"  color: #DFE1E2;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"  border: none;\n"
"  /* The subcontrols below are used only in the DelayedPopup mode */\n"
"  /* The subcontrols below are used only in the MenuButtonPopup mode */\n"
"  /* The subcontrol below is used only in the InstantPopup or DelayedPopup mode */\n"
"}\n"
"\n"
"QToolButton:d"
                        "isabled {\n"
"  background-color: #455364;\n"
"  color: #788D9C;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"  background-color: #60798B;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QToolButton:checked:disabled {\n"
"  background-color: #60798B;\n"
"  color: #788D9C;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QToolButton:checked:hover {\n"
"  background-color: #54687A;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QToolButton:checked:pressed {\n"
"  background-color: #60798B;\n"
"}\n"
"\n"
"QToolButton:checked:selected {\n"
"  background: #60798B;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"  background-color: #54687A;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"  background-color: #60798B;\n"
"}\n"
"\n"
"QToolButton:selected {\n"
"  background: #60798B;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"0\"] {\n"
"  /* Only for DelayedPopup */\n"
"  paddi"
                        "ng-right: 2px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"] {\n"
"  /* Only for MenuButtonPopup */\n"
"  padding-right: 20px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"]::menu-button {\n"
"  border: none;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"]::menu-button:hover {\n"
"  border: none;\n"
"  border-left: 1px solid #455364;\n"
"  border-radius: 0;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"2\"] {\n"
"  /* Only for InstantPopup */\n"
"  padding-right: 2px;\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"  padding: 2px;\n"
"  border-radius: 4px;\n"
"  width: 12px;\n"
"  border: none;\n"
"  outline: none;\n"
"}\n"
"\n"
"QToolButton::menu-button:hover {\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QToolButton::menu-button:checked:hover {\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"  top: 0;\n"
"  /* Exclude a shift for better image */\n"
"  left: -2px;\n"
"  /* Shift it a bit */\n"
"}\n"
""
                        "\n"
"QToolButton::menu-arrow {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QToolButton::menu-arrow:hover {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down_focus.png\");\n"
"}\n"
"\n"
"/* QCommandLinkButton -----------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QCommandLinkButton {\n"
"  background-color: transparent;\n"
"  border: 1px solid #455364;\n"
"  color: #DFE1E2;\n"
"  border-radius: 4px;\n"
"  padding: 0px;\n"
"  margin: 0px;\n"
"}\n"
"\n"
"QCommandLinkButton:disabled {\n"
"  background-color: transparent;\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------------ */\n"
"/* INPUTS - NO FIELDS ----------------------------------------------------- */\n"
"/* ------------------------------------------------------------------------ */\n"
"/* QComboBox ----------------------------------------------"
                        "----------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qcombobox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QComboBox {\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  selection-background-color: #346792;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  /* padding-right = 36; 4 + 16*2 See scrollbar size */\n"
"  /* changed to 4px to fix #239 */\n"
"  /* Fixes #103, #111 */\n"
"  min-height: 1.5em;\n"
"  /* padding-top: 2px;     removed to fix #132 */\n"
"  /* padding-bottom: 2px;  removed to fix #132 */\n"
"  /* min-width: 75px;      removed to fix #109 */\n"
"  /* Needed to remove indicator - fix #132 */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  border: 1px solid #455364;\n"
"  border-radius: 0;\n"
"  background-color: #19232D;\n"
"  selection-background-color: #346792;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView:hover {\n"
"  background-color: #19232D;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QComboBo"
                        "x QAbstractItemView:selected {\n"
"  background: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView:alternate {\n"
"  background: #19232D;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"  background-color: #19232D;\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"  selection-background-color: #346792;\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"  border: none;\n"
"  border-radius: 0;\n"
"  background-color: transparent;\n"
"  selection-background-color: transparent;\n"
"  color: transparent;\n"
"  selection-color: transparent;\n"
"  /* Needed to remove indicator - fix #132 */\n"
"}\n"
"\n"
"QComboBox::indicator:alternate {\n"
"  background: #19232D;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"  /* Remove to fix #282, #285 and MR #288*/\n"
"  /*&:checked {\n"
"            font-weight: bold;\n"
"        }\n"
"\n"
"        &:selected {\n"
"            border: 0px solid "
                        "transparent;\n"
"        }\n"
"        */\n"
"}\n"
"\n"
"QComboBox::item:alternate {\n"
"  background: #19232D;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* QSlider ----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qslider\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QSlider:disabled {\n"
"  background: #19232D;\n"
"}\n"
"\n"
"QSlider:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"  background: #455364;\n"
"  border: 1px solid #455364;\n"
"  height: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"  background: #455364;\n"
"  border: 1px solid #455364;\n"
"  width: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"  background: #346792;\n"
"  border: 1px solid #455364;\n"
"  width: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical"
                        " :disabled {\n"
"  background: #26486B;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"  background: #346792;\n"
"  border: 1px solid #455364;\n"
"  height: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"  background: #26486B;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"  background: #9DA9B5;\n"
"  border: 1px solid #455364;\n"
"  width: 8px;\n"
"  height: 8px;\n"
"  margin: -8px 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"  background: #346792;\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"  background: #9DA9B5;\n"
"  border: 1px solid #455364;\n"
"  width: 8px;\n"
"  height: 8px;\n"
"  margin: 0 -8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"  background: #346792;\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QSlider::handle:vertical:focus {\n"
"  "
                        "border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"/* QLineEdit --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qlineedit\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QLineEdit {\n"
"  background-color: #19232D;\n"
"  padding-top: 2px;\n"
"  /* This QLineEdit fix  103, 111 */\n"
"  padding-bottom: 2px;\n"
"  /* This QLineEdit fix  103, 111 */\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-style: solid;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"  background-color: #19232D;\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 1px solid #346792;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QLineEdit:selected {\n"
"  background-color: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"/* QTabWiget -----------------------------------"
                        "---------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtabwidget-and-qtabbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTabWidget {\n"
"  padding: 2px;\n"
"  selection-background-color: #455364;\n"
"}\n"
"\n"
"QTabWidget QWidget {\n"
"  /* Fixes #189 */\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  margin: 0px;\n"
"  /* Fixes double border inside pane with pyqt5 */\n"
"  padding: 0px;\n"
"}\n"
"\n"
"QTabWidget::pane:selected {\n"
"  background-color: #455364;\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"/* QTabBar ----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtabwidget-and-qtabbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTabBar, QDockWidget QTabBar {\n"
"  qproperty-drawBase: 0;\n"
"  border-radius: "
                        "4px;\n"
"  margin: 0px;\n"
"  padding: 2px;\n"
"  border: 0;\n"
"  /* left: 5px; move to the right by 5px - removed for fix */\n"
"}\n"
"\n"
"QTabBar::close-button, QDockWidget QTabBar::close-button {\n"
"  border: 0;\n"
"  margin: 0;\n"
"  padding: 4px;\n"
"  image: url(\":/qss_icons/dark/rc/window_close.png\");\n"
"}\n"
"\n"
"QTabBar::close-button:hover, QDockWidget QTabBar::close-button:hover {\n"
"  image: url(\":/qss_icons/dark/rc/window_close_focus.png\");\n"
"}\n"
"\n"
"QTabBar::close-button:pressed, QDockWidget QTabBar::close-button:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/window_close_pressed.png\");\n"
"}\n"
"\n"
"QTabBar::tab, QDockWidget QTabBar::tab {\n"
"  /* !selected and disabled ----------------------------------------- */\n"
"  /* selected ------------------------------------------------------- */\n"
"}\n"
"\n"
"QTabBar::tab:top:selected:disabled, QDockWidget QTabBar::tab:top:selected:disabled {\n"
"  border-bottom: 3px solid #26486B;\n"
"  color: #788D9C;\n"
"  background-color: #455"
                        "364;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected:disabled, QDockWidget QTabBar::tab:bottom:selected:disabled {\n"
"  border-top: 3px solid #26486B;\n"
"  color: #788D9C;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected:disabled, QDockWidget QTabBar::tab:left:selected:disabled {\n"
"  border-right: 3px solid #26486B;\n"
"  color: #788D9C;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected:disabled, QDockWidget QTabBar::tab:right:selected:disabled {\n"
"  border-left: 3px solid #26486B;\n"
"  color: #788D9C;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:disabled, QDockWidget QTabBar::tab:top:!selected:disabled {\n"
"  border-bottom: 3px solid #19232D;\n"
"  color: #788D9C;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:disabled, QDockWidget QTabBar::tab:bottom:!selected:disabled {\n"
"  border-top: 3px solid #19232D;\n"
"  color: #788D9C;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QTabBar::tab:left"
                        ":!selected:disabled, QDockWidget QTabBar::tab:left:!selected:disabled {\n"
"  border-right: 3px solid #19232D;\n"
"  color: #788D9C;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected:disabled, QDockWidget QTabBar::tab:right:!selected:disabled {\n"
"  border-left: 3px solid #19232D;\n"
"  color: #788D9C;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected, QDockWidget QTabBar::tab:top:!selected {\n"
"  border-bottom: 2px solid #19232D;\n"
"  margin-top: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected, QDockWidget QTabBar::tab:bottom:!selected {\n"
"  border-top: 2px solid #19232D;\n"
"  margin-bottom: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected, QDockWidget QTabBar::tab:left:!selected {\n"
"  border-left: 2px solid #19232D;\n"
"  margin-right: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected, QDockWidget QTabBar::tab:right:!selected {\n"
"  border-right: 2px solid #19232D;\n"
"  margin-left: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QDockWidget QTabBar::tab:to"
                        "p {\n"
"  background-color: #455364;\n"
"  margin-left: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  padding-top: 2px;\n"
"  padding-bottom: 2px;\n"
"  min-width: 5px;\n"
"  border-bottom: 3px solid #455364;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected, QDockWidget QTabBar::tab:top:selected {\n"
"  background-color: #54687A;\n"
"  border-bottom: 3px solid #259AE9;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover, QDockWidget QTabBar::tab:top:!selected:hover {\n"
"  border: 1px solid #1A72BB;\n"
"  border-bottom: 3px solid #1A72BB;\n"
"  /* Fixes spyder-ide/spyder#9766 and #243 */\n"
"  padding-left: 3px;\n"
"  padding-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom, QDockWidget QTabBar::tab:bottom {\n"
"  border-top: 3px solid #455364;\n"
"  background-color: #455364;\n"
"  margin-left: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  padding-top:"
                        " 2px;\n"
"  padding-bottom: 2px;\n"
"  border-bottom-left-radius: 4px;\n"
"  border-bottom-right-radius: 4px;\n"
"  min-width: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected, QDockWidget QTabBar::tab:bottom:selected {\n"
"  background-color: #54687A;\n"
"  border-top: 3px solid #259AE9;\n"
"  border-bottom-left-radius: 4px;\n"
"  border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:hover, QDockWidget QTabBar::tab:bottom:!selected:hover {\n"
"  border: 1px solid #1A72BB;\n"
"  border-top: 3px solid #1A72BB;\n"
"  /* Fixes spyder-ide/spyder#9766 and #243 */\n"
"  padding-left: 3px;\n"
"  padding-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QDockWidget QTabBar::tab:left {\n"
"  background-color: #455364;\n"
"  margin-top: 2px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"  border-top-left-radius: 4px;\n"
"  border-bottom-left-radius: 4px;\n"
"  min-height: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected, QDockWidget QTabBar::t"
                        "ab:left:selected {\n"
"  background-color: #54687A;\n"
"  border-right: 3px solid #259AE9;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:hover, QDockWidget QTabBar::tab:left:!selected:hover {\n"
"  border: 1px solid #1A72BB;\n"
"  border-right: 3px solid #1A72BB;\n"
"  /* Fixes different behavior #271 */\n"
"  margin-right: 0px;\n"
"  padding-right: -1px;\n"
"}\n"
"\n"
"QTabBar::tab:right, QDockWidget QTabBar::tab:right {\n"
"  background-color: #455364;\n"
"  margin-top: 2px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  border-bottom-right-radius: 4px;\n"
"  min-height: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected, QDockWidget QTabBar::tab:right:selected {\n"
"  background-color: #54687A;\n"
"  border-left: 3px solid #259AE9;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected:hover, QDockWidget QTabBar::tab:right:!selected:hover {\n"
"  border: 1px solid #1A72BB;\n"
"  border-left: 3px solid #1A72BB;\n"
"  /* Fixes dif"
                        "ferent behavior #271 */\n"
"  margin-left: 0px;\n"
"  padding-left: 0px;\n"
"}\n"
"\n"
"QTabBar QToolButton, QDockWidget QTabBar QToolButton {\n"
"  /* Fixes #136 */\n"
"  background-color: #455364;\n"
"  height: 12px;\n"
"  width: 12px;\n"
"}\n"
"\n"
"QTabBar QToolButton:pressed, QDockWidget QTabBar QToolButton:pressed {\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QTabBar QToolButton:pressed:hover, QDockWidget QTabBar QToolButton:pressed:hover {\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:enabled, QDockWidget QTabBar QToolButton::left-arrow:enabled {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_left.png\");\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:disabled, QDockWidget QTabBar QToolButton::left-arrow:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_left_disabled.png\");\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled, QDockWidget QTabBar QToolButton::right-arrow:enabled {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_right.png\");\n"
"}\n"
"\n"
"QTab"
                        "Bar QToolButton::right-arrow:disabled, QDockWidget QTabBar QToolButton::right-arrow:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_right_disabled.png\");\n"
"}\n"
"\n"
"/* QDockWiget -------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QDockWidget {\n"
"  outline: 1px solid #455364;\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  titlebar-close-icon: url(\":/qss_icons/dark/rc/transparent.png\");\n"
"  titlebar-normal-icon: url(\":/qss_icons/dark/rc/transparent.png\");\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"  /* Better size for title bar */\n"
"  padding: 3px;\n"
"  spacing: 4px;\n"
"  border: none;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QDockWidget::close-button {\n"
"  icon-size: 12px;\n"
"  border: none;\n"
"  background: transparent;\n"
"  background-image: transparent;\n"
"  border: 0;\n"
"  margin: 0;\n"
"  padding: 0;\n"
"  image: url(\""
                        ":/qss_icons/dark/rc/window_close.png\");\n"
"}\n"
"\n"
"QDockWidget::close-button:hover {\n"
"  image: url(\":/qss_icons/dark/rc/window_close_focus.png\");\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/window_close_pressed.png\");\n"
"}\n"
"\n"
"QDockWidget::float-button {\n"
"  icon-size: 12px;\n"
"  border: none;\n"
"  background: transparent;\n"
"  background-image: transparent;\n"
"  border: 0;\n"
"  margin: 0;\n"
"  padding: 0;\n"
"  image: url(\":/qss_icons/dark/rc/window_undock.png\");\n"
"}\n"
"\n"
"QDockWidget::float-button:hover {\n"
"  image: url(\":/qss_icons/dark/rc/window_undock_focus.png\");\n"
"}\n"
"\n"
"QDockWidget::float-button:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/window_undock_pressed.png\");\n"
"}\n"
"\n"
"/* QTreeView QListView QTableView -----------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtreeview\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qlistview\n"
""
                        "https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtableview\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTreeView:branch:selected, QTreeView:branch:hover {\n"
"  background: url(\":/qss_icons/dark/rc/transparent.png\");\n"
"}\n"
"\n"
"QTreeView:branch:has-siblings:!adjoins-item {\n"
"  border-image: url(\":/qss_icons/dark/rc/branch_line.png\") 0;\n"
"}\n"
"\n"
"QTreeView:branch:has-siblings:adjoins-item {\n"
"  border-image: url(\":/qss_icons/dark/rc/branch_more.png\") 0;\n"
"}\n"
"\n"
"QTreeView:branch:!has-children:!has-siblings:adjoins-item {\n"
"  border-image: url(\":/qss_icons/dark/rc/branch_end.png\") 0;\n"
"}\n"
"\n"
"QTreeView:branch:has-children:!has-siblings:closed, QTreeView:branch:closed:has-children:has-siblings {\n"
"  border-image: none;\n"
"  image: url(\":/qss_icons/dark/rc/branch_closed.png\");\n"
"}\n"
"\n"
"QTreeView:branch:open:has-children:!has-siblings, QTreeView:branch:open:has-children:has-siblings {\n"
"  border-image: none;\n"
""
                        "  image: url(\":/qss_icons/dark/rc/branch_open.png\");\n"
"}\n"
"\n"
"QTreeView:branch:has-children:!has-siblings:closed:hover, QTreeView:branch:closed:has-children:has-siblings:hover {\n"
"  image: url(\":/qss_icons/dark/rc/branch_closed_focus.png\");\n"
"}\n"
"\n"
"QTreeView:branch:open:has-children:!has-siblings:hover, QTreeView:branch:open:has-children:has-siblings:hover {\n"
"  image: url(\":/qss_icons/dark/rc/branch_open_focus.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:checked,\n"
"QListView::indicator:checked,\n"
"QTableView::indicator:checked,\n"
"QColumnView::indicator:checked {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:checked:hover, QTreeView::indicator:checked:focus, QTreeView::indicator:checked:pressed,\n"
"QListView::indicator:checked:hover,\n"
"QListView::indicator:checked:focus,\n"
"QListView::indicator:checked:pressed,\n"
"QTableView::indicator:checked:hover,\n"
"QTableView::indicator:checked:focus,\n"
"QTableView::indicator:checked:pr"
                        "essed,\n"
"QColumnView::indicator:checked:hover,\n"
"QColumnView::indicator:checked:focus,\n"
"QColumnView::indicator:checked:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked,\n"
"QListView::indicator:unchecked,\n"
"QTableView::indicator:unchecked,\n"
"QColumnView::indicator:unchecked {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked:hover, QTreeView::indicator:unchecked:focus, QTreeView::indicator:unchecked:pressed,\n"
"QListView::indicator:unchecked:hover,\n"
"QListView::indicator:unchecked:focus,\n"
"QListView::indicator:unchecked:pressed,\n"
"QTableView::indicator:unchecked:hover,\n"
"QTableView::indicator:unchecked:focus,\n"
"QTableView::indicator:unchecked:pressed,\n"
"QColumnView::indicator:unchecked:hover,\n"
"QColumnView::indicator:unchecked:focus,\n"
"QColumnView::indicator:unchecked:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked_focus.png\""
                        ");\n"
"}\n"
"\n"
"QTreeView::indicator:indeterminate,\n"
"QListView::indicator:indeterminate,\n"
"QTableView::indicator:indeterminate,\n"
"QColumnView::indicator:indeterminate {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:indeterminate:hover, QTreeView::indicator:indeterminate:focus, QTreeView::indicator:indeterminate:pressed,\n"
"QListView::indicator:indeterminate:hover,\n"
"QListView::indicator:indeterminate:focus,\n"
"QListView::indicator:indeterminate:pressed,\n"
"QTableView::indicator:indeterminate:hover,\n"
"QTableView::indicator:indeterminate:focus,\n"
"QTableView::indicator:indeterminate:pressed,\n"
"QColumnView::indicator:indeterminate:hover,\n"
"QColumnView::indicator:indeterminate:focus,\n"
"QColumnView::indicator:indeterminate:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate_focus.png\");\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView,\n"
"QTableView,\n"
"QColumnView {\n"
"  background-color: #19232D;\n"
"  border: 1px so"
                        "lid #455364;\n"
"  color: #DFE1E2;\n"
"  gridline-color: #455364;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTreeView:disabled,\n"
"QListView:disabled,\n"
"QTableView:disabled,\n"
"QColumnView:disabled {\n"
"  background-color: #19232D;\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"QTreeView:selected,\n"
"QListView:selected,\n"
"QTableView:selected,\n"
"QColumnView:selected {\n"
"  background-color: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"QTreeView:focus,\n"
"QListView:focus,\n"
"QTableView:focus,\n"
"QColumnView:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QTreeView::item:pressed,\n"
"QListView::item:pressed,\n"
"QTableView::item:pressed,\n"
"QColumnView::item:pressed {\n"
"  background-color: #346792;\n"
"}\n"
"\n"
"QTreeView::item:selected:active,\n"
"QListView::item:selected:active,\n"
"QTableView::item:selected:active,\n"
"QColumnView::item:selected:active {\n"
"  background-color: #346792;\n"
"}\n"
"\n"
"QTreeView::item:selected:!active,\n"
"QListView::item:selected:!active,\n"
"QTableView::item:s"
                        "elected:!active,\n"
"QColumnView::item:selected:!active {\n"
"  color: #DFE1E2;\n"
"  background-color: #37414F;\n"
"}\n"
"\n"
"QTreeView::item:!selected:hover,\n"
"QListView::item:!selected:hover,\n"
"QTableView::item:!selected:hover,\n"
"QColumnView::item:!selected:hover {\n"
"  outline: 0;\n"
"  color: #DFE1E2;\n"
"  background-color: #37414F;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"  background-color: #19232D;\n"
"  border: 1px transparent #455364;\n"
"  border-radius: 0px;\n"
"}\n"
"\n"
"/* QHeaderView ------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qheaderview\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QHeaderView {\n"
"  background-color: #455364;\n"
"  border: 0px transparent #455364;\n"
"  padding: 0;\n"
"  margin: 0;\n"
"  border-radius: 0;\n"
"}\n"
"\n"
"QHeaderView:disabled {\n"
"  background-color: #455364;\n"
"  border: 1px transparent #455364;\n"
"}\n"
"\n"
""
                        "QHeaderView::section {\n"
"  background-color: #455364;\n"
"  color: #DFE1E2;\n"
"  border-radius: 0;\n"
"  text-align: left;\n"
"  font-size: 13px;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal {\n"
"  padding-top: 0;\n"
"  padding-bottom: 0;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-left: 1px solid #19232D;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal::first, QHeaderView::section::horizontal::only-one {\n"
"  border-left: 1px solid #455364;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal:disabled {\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"QHeaderView::section::vertical {\n"
"  padding-top: 0;\n"
"  padding-bottom: 0;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-top: 1px solid #19232D;\n"
"}\n"
"\n"
"QHeaderView::section::vertical::first, QHeaderView::section::vertical::only-one {\n"
"  border-top: 1px solid #455364;\n"
"}\n"
"\n"
"QHeaderView::section::vertical:disabled {\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"  /* Those settings (border/w"
                        "idth/height/background-color) solve bug */\n"
"  /* transparent arrow background and size */\n"
"  background-color: #455364;\n"
"  border: none;\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"  background-color: #455364;\n"
"  border: none;\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  image: url(\":/qss_icons/dark/rc/arrow_up.png\");\n"
"}\n"
"\n"
"/* QToolBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtoolbox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolBox {\n"
"  padding: 0px;\n"
"  border: 0px;\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"QToolBox:selected {\n"
"  padding: 0px;\n"
"  border: 2px solid #346792;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"  background-color: #19232D"
                        ";\n"
"  border: 1px solid #455364;\n"
"  color: #DFE1E2;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QToolBox::tab:disabled {\n"
"  color: #788D9C;\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"  background-color: #60798B;\n"
"  border-bottom: 2px solid #346792;\n"
"}\n"
"\n"
"QToolBox::tab:selected:disabled {\n"
"  background-color: #455364;\n"
"  border-bottom: 2px solid #26486B;\n"
"}\n"
"\n"
"QToolBox::tab:!selected {\n"
"  background-color: #455364;\n"
"  border-bottom: 2px solid #455364;\n"
"}\n"
"\n"
"QToolBox::tab:!selected:disabled {\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QToolBox::tab:hover {\n"
"  border-color: #1A72BB;\n"
"  border-bottom: 2px solid #1A72BB;\n"
"}\n"
"\n"
"QToolBox QScrollArea {\n"
"  padding: 0px;\n"
"  border: 0px;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"/* QFrame -----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qframe\n"
"https://doc.qt.i"
                        "o/qt-5/qframe.html#-prop\n"
"https://doc.qt.io/qt-5/qframe.html#details\n"
"https://stackoverflow.com/questions/14581498/qt-stylesheet-for-hline-vline-color\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"/* (dot) .QFrame  fix #141, #126, #123 */\n"
".QFrame {\n"
"  border-radius: 4px;\n"
"  border: 1px solid #455364;\n"
"  /* No frame */\n"
"  /* HLine */\n"
"  /* HLine */\n"
"}\n"
"\n"
".QFrame[frameShape=\"0\"] {\n"
"  border-radius: 4px;\n"
"  border: 1px transparent #455364;\n"
"}\n"
"\n"
".QFrame[frameShape=\"4\"] {\n"
"  max-height: 2px;\n"
"  border: none;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
".QFrame[frameShape=\"5\"] {\n"
"  max-width: 2px;\n"
"  border: none;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"/* QSplitter --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qsplitter\n"
"\n"
"--------------------------------------------------------------------------- */\n"
""
                        "QSplitter {\n"
"  background-color: #455364;\n"
"  spacing: 0px;\n"
"  padding: 0px;\n"
"  margin: 0px;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"  background-color: #455364;\n"
"  border: 0px solid #19232D;\n"
"  spacing: 0px;\n"
"  padding: 1px;\n"
"  margin: 0px;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"  background-color: #9DA9B5;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"  width: 5px;\n"
"  image: url(\":/qss_icons/dark/rc/line_vertical.png\");\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"  height: 5px;\n"
"  image: url(\":/qss_icons/dark/rc/line_horizontal.png\");\n"
"}\n"
"\n"
"/* QDateEdit, QDateTimeEdit -----------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QDateEdit, QDateTimeEdit {\n"
"  selection-background-color: #346792;\n"
"  border-style: solid;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  /* This fixes 103, 111 */\n"
"  padding-top: 2px;\n"
"  /* This fixes 103, 111 */\n"
"  pad"
                        "ding-bottom: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  min-width: 10px;\n"
"}\n"
"\n"
"QDateEdit:on, QDateTimeEdit:on {\n"
"  selection-background-color: #346792;\n"
"}\n"
"\n"
"QDateEdit::drop-down, QDateTimeEdit::drop-down {\n"
"  subcontrol-origin: padding;\n"
"  subcontrol-position: top right;\n"
"  width: 12px;\n"
"  border-left: 1px solid #455364;\n"
"}\n"
"\n"
"QDateEdit::down-arrow, QDateTimeEdit::down-arrow {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down_disabled.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on, QDateEdit::down-arrow:hover, QDateEdit::down-arrow:focus, QDateTimeEdit::down-arrow:on, QDateTimeEdit::down-arrow:hover, QDateTimeEdit::down-arrow:focus {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView, QDateTimeEdit QAbstractItemView {\n"
"  background-color: #19232D;\n"
"  border-radius: 4px;\n"
"  border: 1px solid #455364;\n"
"  selection-background-color: #346792;\n"
"}\n"
"\n"
""
                        "/* QAbstractView ----------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractView:hover {\n"
"  border: 1px solid #346792;\n"
"  color: #DFE1E2;\n"
"}\n"
"\n"
"QAbstractView:selected {\n"
"  background: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"/* PlotWidget -------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"PlotWidget {\n"
"  /* Fix cut labels in plots #134 */\n"
"  padding: 0px;\n"
"}")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout_3 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.left_container_controls_widget = QWidget(self.centralwidget)
        self.left_container_controls_widget.setObjectName(u"left_container_controls_widget")
        self.left_container_controls_widget.setMaximumSize(QSize(400, 1000))
        self.left_container_controls_widget.setStyleSheet(u"border-color: rgb(158, 158, 158);")
        self.verticalLayout_8 = QVBoxLayout(self.left_container_controls_widget)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.tabWidget = QTabWidget(self.left_container_controls_widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMinimumSize(QSize(300, 300))
        self.tabWidget.setMaximumSize(QSize(500, 400))
        self.tabWidget.setStyleSheet(u"")
        self.compose_signal_tab = QWidget()
        self.compose_signal_tab.setObjectName(u"compose_signal_tab")
        self.verticalLayout_10 = QVBoxLayout(self.compose_signal_tab)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.components_label = QLabel(self.compose_signal_tab)
        self.components_label.setObjectName(u"components_label")
        self.components_label.setMinimumSize(QSize(0, 20))
        self.components_label.setMaximumSize(QSize(16777215, 15))

        self.verticalLayout_10.addWidget(self.components_label)

        self.components_listWidget = QListWidget(self.compose_signal_tab)
        self.components_listWidget.setObjectName(u"components_listWidget")
        self.components_listWidget.setMaximumSize(QSize(16777215, 200))

        self.verticalLayout_10.addWidget(self.components_listWidget)

        self.compose_signal_freq_line = QHBoxLayout()
        self.compose_signal_freq_line.setObjectName(u"compose_signal_freq_line")
        self.compose_freq_label = QLabel(self.compose_signal_tab)
        self.compose_freq_label.setObjectName(u"compose_freq_label")
        self.compose_freq_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.compose_signal_freq_line.addWidget(self.compose_freq_label)

        self.compose_freq_slider_complex = QVBoxLayout()
        self.compose_freq_slider_complex.setSpacing(0)
        self.compose_freq_slider_complex.setObjectName(u"compose_freq_slider_complex")
        self.compose_freq_slider = QSlider(self.compose_signal_tab)
        self.compose_freq_slider.setObjectName(u"compose_freq_slider")
        self.compose_freq_slider.setMaximumSize(QSize(250, 16777215))
        self.compose_freq_slider.setTabletTracking(False)
        self.compose_freq_slider.setMaximum(80)
        self.compose_freq_slider.setTracking(True)
        self.compose_freq_slider.setOrientation(Qt.Horizontal)
        self.compose_freq_slider.setInvertedAppearance(False)
        self.compose_freq_slider.setInvertedControls(False)
        self.compose_freq_slider.setTickPosition(QSlider.TicksBelow)
        self.compose_freq_slider.setTickInterval(0)

        self.compose_freq_slider_complex.addWidget(self.compose_freq_slider)

        self.compose_freq_labels_0_to_100 = QHBoxLayout()
        self.compose_freq_labels_0_to_100.setObjectName(u"compose_freq_labels_0_to_100")
        self.compose_freq_1_label = QLabel(self.compose_signal_tab)
        self.compose_freq_1_label.setObjectName(u"compose_freq_1_label")
        self.compose_freq_1_label.setMaximumSize(QSize(500, 16777215))

        self.compose_freq_labels_0_to_100.addWidget(self.compose_freq_1_label)

        self.compose_freq_100_label = QLabel(self.compose_signal_tab)
        self.compose_freq_100_label.setObjectName(u"compose_freq_100_label")
        self.compose_freq_100_label.setMaximumSize(QSize(30, 16777215))
        self.compose_freq_100_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.compose_freq_100_label.setIndent(0)

        self.compose_freq_labels_0_to_100.addWidget(self.compose_freq_100_label)


        self.compose_freq_slider_complex.addLayout(self.compose_freq_labels_0_to_100)


        self.compose_signal_freq_line.addLayout(self.compose_freq_slider_complex)

        self.compose_hz_label = QLabel(self.compose_signal_tab)
        self.compose_hz_label.setObjectName(u"compose_hz_label")
        self.compose_hz_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.compose_signal_freq_line.addWidget(self.compose_hz_label)


        self.verticalLayout_10.addLayout(self.compose_signal_freq_line)

        self.compose_signal_phase_line = QHBoxLayout()
        self.compose_signal_phase_line.setObjectName(u"compose_signal_phase_line")
        self.compose_phase_label = QLabel(self.compose_signal_tab)
        self.compose_phase_label.setObjectName(u"compose_phase_label")
        self.compose_phase_label.setMaximumSize(QSize(55, 16777215))
        self.compose_phase_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.compose_signal_phase_line.addWidget(self.compose_phase_label)

        self.compose_phase_slider_complex = QVBoxLayout()
        self.compose_phase_slider_complex.setSpacing(0)
        self.compose_phase_slider_complex.setObjectName(u"compose_phase_slider_complex")
        self.compose_phase_slider_complex.setContentsMargins(0, -1, -1, -1)
        self.compose_phase_slider = QSlider(self.compose_signal_tab)
        self.compose_phase_slider.setObjectName(u"compose_phase_slider")
        self.compose_phase_slider.setMaximumSize(QSize(160, 16777215))
        self.compose_phase_slider.setMaximum(200)
        self.compose_phase_slider.setSingleStep(1)
        self.compose_phase_slider.setOrientation(Qt.Horizontal)
        self.compose_phase_slider.setTickPosition(QSlider.TicksBelow)
        self.compose_phase_slider.setTickInterval(0)

        self.compose_phase_slider_complex.addWidget(self.compose_phase_slider)

        self.phase_labels_0_to_100 = QHBoxLayout()
        self.phase_labels_0_to_100.setObjectName(u"phase_labels_0_to_100")
        self.phase_label_0 = QLabel(self.compose_signal_tab)
        self.phase_label_0.setObjectName(u"phase_label_0")
        self.phase_label_0.setIndent(0)

        self.phase_labels_0_to_100.addWidget(self.phase_label_0)

        self.phase_label_pi = QLabel(self.compose_signal_tab)
        self.phase_label_pi.setObjectName(u"phase_label_pi")
        self.phase_label_pi.setIndent(6)

        self.phase_labels_0_to_100.addWidget(self.phase_label_pi)

        self.phase_label_2_pi = QLabel(self.compose_signal_tab)
        self.phase_label_2_pi.setObjectName(u"phase_label_2_pi")
        self.phase_label_2_pi.setMaximumSize(QSize(30, 16777215))
        self.phase_label_2_pi.setToolTipDuration(-1)
        self.phase_label_2_pi.setLayoutDirection(Qt.LeftToRight)
        self.phase_label_2_pi.setLineWidth(0)
        self.phase_label_2_pi.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.phase_label_2_pi.setIndent(0)

        self.phase_labels_0_to_100.addWidget(self.phase_label_2_pi)


        self.compose_phase_slider_complex.addLayout(self.phase_labels_0_to_100)


        self.compose_signal_phase_line.addLayout(self.compose_phase_slider_complex)

        self.compose_amplitude_label = QLabel(self.compose_signal_tab)
        self.compose_amplitude_label.setObjectName(u"compose_amplitude_label")
        self.compose_amplitude_label.setMinimumSize(QSize(65, 0))
        self.compose_amplitude_label.setMaximumSize(QSize(70, 16777215))
        self.compose_amplitude_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.compose_signal_phase_line.addWidget(self.compose_amplitude_label)

        self.compose_amplitude_spin_box = QDoubleSpinBox(self.compose_signal_tab)
        self.compose_amplitude_spin_box.setObjectName(u"compose_amplitude_spin_box")
        self.compose_amplitude_spin_box.setMaximumSize(QSize(70, 16777215))
        self.compose_amplitude_spin_box.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.compose_signal_phase_line.addWidget(self.compose_amplitude_spin_box)


        self.verticalLayout_10.addLayout(self.compose_signal_phase_line)

        self.add_component_button = QPushButton(self.compose_signal_tab)
        self.add_component_button.setObjectName(u"add_component_button")

        self.verticalLayout_10.addWidget(self.add_component_button)

        self.tabWidget.addTab(self.compose_signal_tab, "")
        self.load_file_tab = QWidget()
        self.load_file_tab.setObjectName(u"load_file_tab")
        self.horizontalLayout = QHBoxLayout(self.load_file_tab)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer = QSpacerItem(10, 10, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.browse_csv_button = QPushButton(self.load_file_tab)
        self.browse_csv_button.setObjectName(u"browse_csv_button")
        self.browse_csv_button.setMinimumSize(QSize(150, 50))

        self.horizontalLayout.addWidget(self.browse_csv_button)

        self.horizontalSpacer_2 = QSpacerItem(10, 10, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.tabWidget.addTab(self.load_file_tab, "")

        self.verticalLayout_8.addWidget(self.tabWidget)

        self.frame = QFrame(self.left_container_controls_widget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.snr_line = QHBoxLayout()
        self.snr_line.setObjectName(u"snr_line")
        self.snr_label = QLabel(self.frame)
        self.snr_label.setObjectName(u"snr_label")
        self.snr_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.snr_line.addWidget(self.snr_label)

        self.snr_signal_slider_complex = QVBoxLayout()
        self.snr_signal_slider_complex.setObjectName(u"snr_signal_slider_complex")
        self.snr_slider = QSlider(self.frame)
        self.snr_slider.setObjectName(u"snr_slider")
        self.snr_slider.setMaximumSize(QSize(250, 16777215))
        self.snr_slider.setMaximum(19)
        self.snr_slider.setOrientation(Qt.Horizontal)
        self.snr_slider.setTickPosition(QSlider.TicksBelow)
        self.snr_slider.setTickInterval(10)

        self.snr_signal_slider_complex.addWidget(self.snr_slider)

        self.snr_labels_0_to_100 = QHBoxLayout()
        self.snr_labels_0_to_100.setObjectName(u"snr_labels_0_to_100")
        self.snr_1_label = QLabel(self.frame)
        self.snr_1_label.setObjectName(u"snr_1_label")
        self.snr_1_label.setMaximumSize(QSize(70, 16777215))
        self.snr_1_label.setIndent(0)

        self.snr_labels_0_to_100.addWidget(self.snr_1_label)

        self.snr_label_5 = QLabel(self.frame)
        self.snr_label_5.setObjectName(u"snr_label_5")

        self.snr_labels_0_to_100.addWidget(self.snr_label_5)

        self.snr_label_10 = QLabel(self.frame)
        self.snr_label_10.setObjectName(u"snr_label_10")

        self.snr_labels_0_to_100.addWidget(self.snr_label_10)

        self.snr_label_50 = QLabel(self.frame)
        self.snr_label_50.setObjectName(u"snr_label_50")

        self.snr_labels_0_to_100.addWidget(self.snr_label_50)

        self.snr_100_label = QLabel(self.frame)
        self.snr_100_label.setObjectName(u"snr_100_label")
        self.snr_100_label.setMinimumSize(QSize(25, 0))
        self.snr_100_label.setMaximumSize(QSize(20, 16777215))
        self.snr_100_label.setLayoutDirection(Qt.RightToLeft)
        self.snr_100_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.snr_100_label.setIndent(0)

        self.snr_labels_0_to_100.addWidget(self.snr_100_label)


        self.snr_signal_slider_complex.addLayout(self.snr_labels_0_to_100)


        self.snr_line.addLayout(self.snr_signal_slider_complex)

        self.show_noise_checkBox = QCheckBox(self.frame)
        self.show_noise_checkBox.setObjectName(u"show_noise_checkBox")

        self.snr_line.addWidget(self.show_noise_checkBox)


        self.verticalLayout_2.addLayout(self.snr_line)

        self.line_2 = QFrame(self.frame)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setStyleSheet(u"background-color: rgb(158, 158, 158);")
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_2.addWidget(self.line_2)

        self.signals_sampling_freq_line = QHBoxLayout()
        self.signals_sampling_freq_line.setObjectName(u"signals_sampling_freq_line")
        self.sampling_freq_label = QLabel(self.frame)
        self.sampling_freq_label.setObjectName(u"sampling_freq_label")

        self.signals_sampling_freq_line.addWidget(self.sampling_freq_label)

        self.sampling_freq_comboBox = QComboBox(self.frame)
        self.sampling_freq_comboBox.setObjectName(u"sampling_freq_comboBox")

        self.signals_sampling_freq_line.addWidget(self.sampling_freq_comboBox)

        self.f_max_label = QLabel(self.frame)
        self.f_max_label.setObjectName(u"f_max_label")
        self.f_max_label.setTextFormat(Qt.MarkdownText)

        self.signals_sampling_freq_line.addWidget(self.f_max_label)

        self.show_samples_checkBox = QCheckBox(self.frame)
        self.show_samples_checkBox.setObjectName(u"show_samples_checkBox")

        self.signals_sampling_freq_line.addWidget(self.show_samples_checkBox)


        self.verticalLayout_2.addLayout(self.signals_sampling_freq_line)

        self.line_3 = QFrame(self.frame)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setStyleSheet(u"background-color: rgb(158, 158, 158);")
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_2.addWidget(self.line_3)

        self.reconstruction_method_line = QHBoxLayout()
        self.reconstruction_method_line.setSpacing(0)
        self.reconstruction_method_line.setObjectName(u"reconstruction_method_line")
        self.reconstruction_method_label = QLabel(self.frame)
        self.reconstruction_method_label.setObjectName(u"reconstruction_method_label")

        self.reconstruction_method_line.addWidget(self.reconstruction_method_label)

        self.reconstruction_method_comboBox = QComboBox(self.frame)
        self.reconstruction_method_comboBox.setObjectName(u"reconstruction_method_comboBox")

        self.reconstruction_method_line.addWidget(self.reconstruction_method_comboBox)


        self.verticalLayout_2.addLayout(self.reconstruction_method_line)


        self.verticalLayout_8.addWidget(self.frame)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.verticalLayout_8.addItem(self.horizontalSpacer_4)


        self.horizontalLayout_3.addWidget(self.left_container_controls_widget)

        self.right_container = QVBoxLayout()
        self.right_container.setSpacing(0)
        self.right_container.setObjectName(u"right_container")
        self.grid_list_buttons = QWidget(self.centralwidget)
        self.grid_list_buttons.setObjectName(u"grid_list_buttons")
        self.grid_list_buttons.setMaximumSize(QSize(75, 30))
        self.grid_list_buttons.setLayoutDirection(Qt.RightToLeft)
        self.horizontalLayout_2 = QHBoxLayout(self.grid_list_buttons)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.grid_view_button = QPushButton(self.grid_list_buttons)
        self.grid_view_button.setObjectName(u"grid_view_button")
        self.grid_view_button.setEnabled(False)
        self.grid_view_button.setMaximumSize(QSize(40, 30))
        icon = QIcon()
        icon.addFile(u"grid_view.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.grid_view_button.setIcon(icon)

        self.horizontalLayout_2.addWidget(self.grid_view_button)

        self.list_view_button = QPushButton(self.grid_list_buttons)
        self.list_view_button.setObjectName(u"list_view_button")
        self.list_view_button.setMaximumSize(QSize(40, 30))
        icon1 = QIcon()
        icon1.addFile(u"list_view.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.list_view_button.setIcon(icon1)

        self.horizontalLayout_2.addWidget(self.list_view_button)


        self.right_container.addWidget(self.grid_list_buttons)

        self.ay_7aga = QWidget(self.centralwidget)
        self.ay_7aga.setObjectName(u"ay_7aga")
        self.graphs_layout = QHBoxLayout(self.ay_7aga)
        self.graphs_layout.setSpacing(0)
        self.graphs_layout.setObjectName(u"graphs_layout")
        self.left_vertical_layout = QVBoxLayout()
        self.left_vertical_layout.setSpacing(0)
        self.left_vertical_layout.setObjectName(u"left_vertical_layout")
        self.left_vertical_layout.setContentsMargins(-1, 0, -1, -1)
        self.top_left_widget = QWidget(self.ay_7aga)
        self.top_left_widget.setObjectName(u"top_left_widget")
        self.top_left_widget.setMinimumSize(QSize(300, 150))
        self.top_left_widget.setMaximumSize(QSize(600, 300))
        self.verticalLayout = QVBoxLayout(self.top_left_widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)

        self.left_vertical_layout.addWidget(self.top_left_widget)

        self.bottom_left_widget = QWidget(self.ay_7aga)
        self.bottom_left_widget.setObjectName(u"bottom_left_widget")
        self.bottom_left_widget.setMinimumSize(QSize(300, 150))
        self.bottom_left_widget.setMaximumSize(QSize(600, 300))
        self.bottom_left_widget.setStyleSheet(u"border-color: rgb(255, 255, 255);")
        self.verticalLayout_4 = QVBoxLayout(self.bottom_left_widget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)

        self.left_vertical_layout.addWidget(self.bottom_left_widget)


        self.graphs_layout.addLayout(self.left_vertical_layout)

        self.right_vertical_layout = QVBoxLayout()
        self.right_vertical_layout.setObjectName(u"right_vertical_layout")
        self.top_right_widget = QWidget(self.ay_7aga)
        self.top_right_widget.setObjectName(u"top_right_widget")
        self.top_right_widget.setMinimumSize(QSize(300, 150))
        self.top_right_widget.setMaximumSize(QSize(600, 300))
        self.verticalLayout_5 = QVBoxLayout(self.top_right_widget)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)

        self.right_vertical_layout.addWidget(self.top_right_widget)

        self.bottom_right_widget = QWidget(self.ay_7aga)
        self.bottom_right_widget.setObjectName(u"bottom_right_widget")
        self.bottom_right_widget.setMinimumSize(QSize(300, 150))
        self.bottom_right_widget.setMaximumSize(QSize(600, 300))
        self.verticalLayout_3 = QVBoxLayout(self.bottom_right_widget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)

        self.right_vertical_layout.addWidget(self.bottom_right_widget)


        self.graphs_layout.addLayout(self.right_vertical_layout)


        self.right_container.addWidget(self.ay_7aga)


        self.horizontalLayout_3.addLayout(self.right_container)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1080, 31))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.components_label.setText(QCoreApplication.translate("MainWindow", u"Components:", None))
        self.compose_freq_label.setText(QCoreApplication.translate("MainWindow", u"Frequency", None))
        self.compose_freq_1_label.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.compose_freq_100_label.setText(QCoreApplication.translate("MainWindow", u"80", None))
        self.compose_hz_label.setText(QCoreApplication.translate("MainWindow", u"Hz", None))
        self.compose_phase_label.setText(QCoreApplication.translate("MainWindow", u"Phase", None))
        self.phase_label_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.phase_label_pi.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>&#8508;</p></body></html>", None))
        self.phase_label_2_pi.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>2 &#8508;</p></body></html>", None))
        self.compose_amplitude_label.setText(QCoreApplication.translate("MainWindow", u"Amplitude", None))
        self.add_component_button.setText(QCoreApplication.translate("MainWindow", u"Add Component", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.compose_signal_tab), QCoreApplication.translate("MainWindow", u"Compose Signal", None))
        self.browse_csv_button.setText(QCoreApplication.translate("MainWindow", u"Load CSV", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.load_file_tab), QCoreApplication.translate("MainWindow", u"Load File", None))
        self.snr_label.setText(QCoreApplication.translate("MainWindow", u"SNR", None))
        self.snr_1_label.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.snr_label_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.snr_label_10.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.snr_label_50.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.snr_100_label.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.show_noise_checkBox.setText(QCoreApplication.translate("MainWindow", u"Show Noise", None))
        self.sampling_freq_label.setText(QCoreApplication.translate("MainWindow", u"Sampling Frequency", None))
        self.f_max_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">&#215; F</span><span style=\" font-size:12pt; vertical-align:sub;\">max</span></p></body></html>", None))
        self.show_samples_checkBox.setText(QCoreApplication.translate("MainWindow", u"Show Samples", None))
        self.reconstruction_method_label.setText(QCoreApplication.translate("MainWindow", u"Reconstruction Method:", None))
        self.grid_view_button.setText("")
        self.list_view_button.setText("")
    # retranslateUi

